---
# tasks file for gitlab
- name: Install required packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev
    - curl
    - cmake
    - openssh-server
    - redis-server
    - checkinstall
    - libxml2-dev
    - libxslt-dev
    - libcurl4-openssl-dev
    - libicu-dev
    - logrotate
    - python-docutils
    - pkg-config
    - libkrb5-dev
    - exim4
    - libpq-dev
    - python-psycopg2
    - nginx
    - redis-server

- name: Install git version 1.9.1
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - git-man=1:1.9.1-1~bpo70+2
    - git=1:1.9.1-1~bpo70+2

- name: Configure Exim4
  lineinfile:
    dest: /etc/exim4/update-exim4.conf.conf
    regexp: "dc_eximconfig_configtype='.+?'"
    line: "dc_eximconfig_configtype='internet'"
  notify: restart exim4

- name: Configure Exim4 (local address)
  lineinfile:
    dest: /etc/exim4/update-exim4.conf.conf
    regexp: "dc_other_hostnames='.+?'"
    line: "dc_other_hostnames='{{ web_domain }}'"
  notify: restart exim4

- name: Configure Exim4 mailname
  lineinfile:
    dest: /etc/mailname
    line: "{{ web_domain }}"
    create: yes
    owner: root
    group: root
    mode: 0644
  notify: restart exim4

- name: Remove old ruby1.8
  apt:
    pkg: ruby1.8
    state: absent
