---
# tasks file for gitlab
- name: Install required packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev
    - curl
    - openssh-server
    - redis-server
    - checkinstall
    - libxml2-dev
    - libxslt-dev
    - libcurl4-openssl-dev
    - libicu-dev
    - logrotate
    - git-core
    - exim4
    - postgresql-9.1
    - postgresql-client
    - libpq-dev
    - python-psycopg2
    - nginx

- name: Configure Exim4
  lineinfile:
    dest: /etc/exim4/update-exim4.conf.conf
    regexp: "dc_eximconfig_configtype='.+?'"
    line: "dc_eximconfig_configtype='internet'"
  notify: restart exim4

- name: Configure Exim4 mailname
  lineinfile:
    dest: /etc/mailname
    line: "{{ web_domain }}"
    create: yes
    owner: root
    group: root
    mode: 0644
  notify: restart exim4

- name: Remove old ruby1.8
  apt:
    pkg: ruby1.8
    state: absent