---
# tasks file for gitlab
- name: Install required packages
  apt:
    pkg="{{ item }}"
    state=latest
  with_items:
    - build-essential
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev
    - curl
    - openssh-server
    - redis-server
    - checkinstall
    - libxml2-dev
    - libxslt-dev
    - libcurl4-openssl-dev
    - libicu-dev
    - logrotate
    - git-core
    - exim4
    - postgresql-9.1
    - postgresql-client
    - libpq-dev
    - python-psycopg2
    - nginx

- name: Configure Exim4
  lineinfile:
    dest=/etc/exim4/update-exim4.conf.conf
    regexp="dc_eximconfig_configtype='.+?'"
    line="dc_eximconfig_configtype='internet'"
  notify: restart exim4

- name: Configure Exim4 mailname
  lineinfile:
    dest=/etc/mailname
    line="{{ web_domain }}"
    create=yes
    owner=root
    group=root
    mode=0644
  notify: restart exim4

- name: Remove old ruby1.8
  apt:
    pkg=ruby1.8
    state=absent

- name: Check if ruby is installed
  stat:
    path=/usr/local/lib/ruby/gems/2.0.0
  register: ruby

- name: Install ruby from source
  include: ruby.yml
  when: not ruby.stat.exists

- name: Add git user
  user:
    name=git
    comment=GitLab
    state=present

- name: Get gitlab-shell
  git:
    dest=/home/git/gitlab-shell
    repo=https://gitlab.com/gitlab-org/gitlab-shell.git
    version=v1.9.3
  sudo_user: git

- name: Copy the configuration sample
  command: cp config.yml.example config.yml
    chdir=/home/git/gitlab-shell
  sudo_user: git

- name: Change the gitlab_url
  lineinfile:
    dest=/home/git/gitlab-shell/config.yml
    regexp='^(gitlab_url:)( \"http://)'
    backrefs=yes
    line='\1\2{{ web_domain }}/"'
  sudo_user: git

- name: Setup gitlab-shell
  command: ./bin/install
    chdir=/home/git/gitlab-shell
  sudo_user: git

- name: Create gitlab database user
  postgresql_user:
    name=git
  sudo_user: postgres

- name: Create gitlab database
  postgresql_db:
    name=gitlabhq_production
    owner=git
  sudo_user: postgres

- name: Get gitlab
  git:
    dest=/tmp/gitlab
    repo=ssh://gitlab@git.forgeservicelab.fi:10022/forge/gitlab-ce.git
    ssh_opts="-o StrictHostKeyChecking=no"
  sudo: false

- name: Move Gitlab to its final location
  command: cp -r /tmp/gitlab ~
  sudo_user: git

- name: Ensure permissions on log and tmp
  file:
    dest="/home/git/gitlab/{{ item }}"
    owner=git
    mode=0755
    state=directory
    recurse=yes
  with_items:
    - 'log'
    - 'tmp'
    - 'tmp/pids'
    - 'tmp/sockets'
    - 'public/uploads'

- name: Copy the Unicorn config file
  command: cp config/unicorn.rb.example config/unicorn.rb
    chdir=/home/git/gitlab
  sudo_user: git

- name: Copy the Rack attack config file
  command: cp config/initializers/rack_attack.rb.example config/initializers/rack_attack.rb
    chdir=/home/git/gitlab
  sudo_user: git

- name: Configure git settings
  command: "git config --global {{ item }}"
  sudo_user: git
  with_items:
    - 'user.name "GitLab"'
    - 'user.email "gitlab@{{ web_domain }}"'
    - 'core.autocrlf input'

- name: Copy the database config file
  command: cp config/database.yml.postgresql config/database.yml
    chdir=/home/git/gitlab
  sudo_user: git

- name: Ensure database config permissions
  file:
    dest=/home/git/gitlab/config/database.yml
    owner=git
    mode=0750

- name: Create satellites directory
  file:
    dest=/home/git/gitlab-satellites
    owner=git
    mode=0750

- name: Install gems
  command: bundle install --deployment --without development test mysql aws
    chdir=/home/git/gitlab
  sudo_user: git

- name: Install init.d script
  command: cp lib/support/init.d/gitlab /etc/init.d/gitlab
    chdir=/home/git/gitlab
    creates=/etc/init.d/gitlab

- name: Add gitlab to startup pipeline
  command: update-rc.d gitlab defaults 21

- name: Setup logrotate
  command: cp lib/support/logrotate/gitlab /etc/logrotate.d/gitlab
    chdir=/home/git/gitlab
    creates=/etc/logrotate.d/gitlab

- name: Configure nginx
  command: cp lib/support/nginx/gitlab /etc/nginx/sites-available/gitlab
    chdir=/home/git/gitlab
    creates=/etc/nginx/sites-available/gitlab
  notify: restart nginx

- name: Enable gitlab nginx config
  file:
    src=../sites-available/gitlab
    dest=/etc/nginx/sites-enabled/gitlab
    state=link
  notify: restart nginx
