---
# handlers file for gitlab
- name: restart exim4
  service:
    name: exim4
    state: restarted

- name: restart postgresql
  service:
    name: postgresql
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart gitlab
  service:
    name: gitlab
    state: restarted
